coverage:
  precision: 1
  round: down
  range: "30...100"

  status:
    project:
      default:
        enabled: yes
        target: 30%
    patch:
      default:
        enabled: yes
        target: 60%
    changes:
      default:
        enabled: no

comment:
  # diff, changes, footer, reach, flags, suggestions,
  layout: "header, sunburst, tree, files"