# https://github.com/andstatus/andstatus/blob/master/.travis.yml

language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    # Run android tests on api level 22
    - EMULATOR_API=22
    - EMULATOR_ABI=armeabi-v7a
    - EMULATOR_TAG=default
    - PATH=$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$PATH

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - doc-26

install:
  # Setup
  - echo $ANDROID_HOME # We assume this is correctly set when setting path
  - sdkmanager --list || true # Look at the packages
  - echo yes | sdkmanager "tools" # Ensure tools is updated
  - echo yes | sdkmanager "emulator" # Ensure emulator is present

  # Install emulator
  - export EMULATOR="system-images;android-$EMULATOR_API;$EMULATOR_TAG;$EMULATOR_ABI"
  - echo yes | sdkmanager "platforms;android-$EMULATOR_API" # Install sdk
  - echo yes | sdkmanager "$EMULATOR" # Install system image

  # Create adn start emulator
  - echo no | avdmanager create avd -n test -k "$EMULATOR" -f # Create emulator
  - emulator -avd test -no-window -camera-back emulated -camera-front emulated -memory 2048 & # Launch
  - adb wait-for-device # Wait for adb process
  - sdkmanager --list || true # Check everything is updated

before_script:
  - android-wait-for-emulator # Wait for emulator ready to interact
  - adb shell settings put global window_animation_scale 0 & # Disable animations
  - adb shell settings put global transition_animation_scale 0 & # Disable animations
  - adb shell settings put global animator_duration_scale 0 & # Disable animations
  - sleep 20 # Sleep 20 seconds just in case
  - adb shell input keyevent 82 & # Dispatch event

script:
  - ./gradlew clean testDebugUnitTest
  - adb logcat -c
  - adb logcat -v color Test:V TestRunner:V CameraView:V CameraController:V Camera1:V WorkerHandler:V *:S &
  - export LOGCAT_PID=$!
  - ./gradlew connectedCheck
  - kill $LOGCAT_PID
  - ./gradlew mergedCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -s "*/build/reports/mergedCoverageReport/"

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true